apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - host: {{ .Values.ingress.hostName }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.name }}
              servicePort: http
