apiVersion: v1
kind: Secret
metadata:
  name: {{ default "backend-db" .Values.secret.name }}
type: Opaque
stringData:
  database_mongodb_uri: {{ required "A URI do banco de dados é obrigatória" .Values.secret.mongodb_uri }}
